-- CHESS IN TIME — FASE 8a
-- Semilla de aperturas para el esquema chess_in_time.
-- Misma fuente que opening_book.dart: teoría de ajedrez pública (códigos ECO
-- estándar), sin contenido de libros con copyright específico.

CREATE TABLE IF NOT EXISTS chess_in_time.aperturas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    eco TEXT NOT NULL,
    nombre TEXT NOT NULL,
    jugadas TEXT[] NOT NULL, -- en SAN, en orden
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO chess_in_time.aperturas (eco, nombre, jugadas) VALUES
('A00', 'Apertura Polaca (Sokolsky)', ARRAY['b4']),
('A01', 'Apertura Larsen', ARRAY['b3']),
('A02', 'Apertura Bird', ARRAY['f4']),
('A04', 'Apertura Réti', ARRAY['Nf3']),
('A10', 'Apertura Inglesa', ARRAY['c4']),
('A13', 'Inglesa: Sistema Agincourt', ARRAY['c4','e6','Nf3']),
('A45', 'Apertura de Peón Dama, Ataque Trompowsky', ARRAY['d4','Nf6','Bg5']),
('A56', 'Defensa Benoni', ARRAY['d4','Nf6','c4','c5']),
('A57', 'Gambito Benko', ARRAY['d4','Nf6','c4','c5','d5','b5']),
('A80', 'Defensa Holandesa', ARRAY['d4','f5']),
('B00', 'Defensa Nimzowitsch (1...Cc6)', ARRAY['e4','Nc6']),
('B01', 'Defensa Escandinava', ARRAY['e4','d5']),
('B02', 'Defensa Alekhine', ARRAY['e4','Nf6']),
('B06', 'Defensa Moderna', ARRAY['e4','g6']),
('B07', 'Defensa Pirc', ARRAY['e4','d6','d4','Nf6']),
('B10', 'Defensa Caro-Kann', ARRAY['e4','c6']),
('B12', 'Caro-Kann: Ataque Avance', ARRAY['e4','c6','d4','d5','e5']),
('B20', 'Defensa Siciliana', ARRAY['e4','c5']),
('B21', 'Siciliana: Gambito Smith-Morra', ARRAY['e4','c5','d4','cxd4','c3']),
('B22', 'Siciliana: Variante Alapin', ARRAY['e4','c5','c3']),
('B23', 'Siciliana Cerrada', ARRAY['e4','c5','Nc3']),
('B27', 'Siciliana: Hyperaccelerated Dragon', ARRAY['e4','c5','Nf3','g6']),
('B30', 'Siciliana: Variante Rossolimo', ARRAY['e4','c5','Nf3','Nc6','Bb5']),
('B32', 'Siciliana: Variante Sveshnikov', ARRAY['e4','c5','Nf3','Nc6','d4','cxd4','Nxd4','Nf6','Nc3','e5']),
('B40', 'Siciliana: Variante Kan', ARRAY['e4','c5','Nf3','e6','d4','cxd4','Nxd4','a6']),
('B50', 'Siciliana: Sistema Cerrado con d3', ARRAY['e4','c5','Nf3','d6','d3']),
('B70', 'Siciliana Dragón', ARRAY['e4','c5','Nf3','d6','d4','cxd4','Nxd4','Nf6','Nc3','g6']),
('B90', 'Siciliana Najdorf', ARRAY['e4','c5','Nf3','d6','d4','cxd4','Nxd4','Nf6','Nc3','a6']),
('C00', 'Defensa Francesa', ARRAY['e4','e6']),
('C02', 'Francesa: Variante de Avance', ARRAY['e4','e6','d4','d5','e5']),
('C10', 'Francesa: Variante Rubinstein', ARRAY['e4','e6','d4','d5','Nc3','dxe4']),
('C15', 'Francesa: Variante Winawer', ARRAY['e4','e6','d4','d5','Nc3','Bb4']),
('C20', 'Apertura del Peón de Rey', ARRAY['e4','e5']),
('C23', 'Apertura del Alfil', ARRAY['e4','e5','Bc4']),
('C25', 'Apertura Vienesa', ARRAY['e4','e5','Nc3']),
('C30', 'Gambito de Rey', ARRAY['e4','e5','f4']),
('C41', 'Defensa Philidor', ARRAY['e4','e5','Nf3','d6']),
('C42', 'Defensa Petrov (Rusa)', ARRAY['e4','e5','Nf3','Nf6']),
('C44', 'Apertura Escocesa', ARRAY['e4','e5','Nf3','Nc6','d4']),
('C45', 'Escocesa: Variante Clásica', ARRAY['e4','e5','Nf3','Nc6','d4','exd4','Nxd4']),
('C50', 'Apertura Italiana (Giuoco Piano)', ARRAY['e4','e5','Nf3','Nc6','Bc4','Bc5']),
('C51', 'Gambito Evans', ARRAY['e4','e5','Nf3','Nc6','Bc4','Bc5','b4']),
('C55', 'Ataque de los Dos Caballos', ARRAY['e4','e5','Nf3','Nc6','Bc4','Nf6']),
('C57', 'Ataque Fried Liver / Traxler', ARRAY['e4','e5','Nf3','Nc6','Bc4','Nf6','Ng5']),
('C60', 'Apertura Española (Ruy López)', ARRAY['e4','e5','Nf3','Nc6','Bb5']),
('C65', 'Española: Defensa Berlinesa', ARRAY['e4','e5','Nf3','Nc6','Bb5','Nf6']),
('C68', 'Española: Variante de Cambio', ARRAY['e4','e5','Nf3','Nc6','Bb5','a6','Bxc6']),
('C78', 'Española: Variante Arkhangelsk', ARRAY['e4','e5','Nf3','Nc6','Bb5','a6','Ba4','Nf6','O-O','b5','Bb3','Bb7']),
('C84', 'Española: Variante Cerrada', ARRAY['e4','e5','Nf3','Nc6','Bb5','a6','Ba4','Nf6','O-O','Be7']),
('D00', 'Apertura de Peón Dama', ARRAY['d4','d5']),
('D02', 'Sistema Londres', ARRAY['d4','d5','Nf3','Nf6','Bf4']),
('D06', 'Gambito de Dama', ARRAY['d4','d5','c4']),
('D07', 'Gambito de Dama: Defensa Chigorin', ARRAY['d4','d5','c4','Nc6']),
('D20', 'Gambito de Dama Aceptado', ARRAY['d4','d5','c4','dxc4']),
('D30', 'Gambito de Dama Rehusado', ARRAY['d4','d5','c4','e6']),
('D31', 'GDR: Semi-Eslava (preparación)', ARRAY['d4','d5','c4','e6','Nc3','c6']),
('D35', 'GDR: Variante de Cambio', ARRAY['d4','d5','c4','e6','Nc3','Nf6','cxd5','exd5']),
('D43', 'Defensa Semi-Eslava', ARRAY['d4','d5','c4','c6','Nc3','Nf6','Nf3','e6']),
('D80', 'Defensa Grünfeld', ARRAY['d4','Nf6','c4','g6','Nc3','d5']),
('E00', 'Sistema Catalán', ARRAY['d4','Nf6','c4','e6','g3']),
('E12', 'Defensa India de Dama', ARRAY['d4','Nf6','c4','e6','Nf3','b6']),
('E20', 'Defensa Nimzoindia', ARRAY['d4','Nf6','c4','e6','Nc3','Bb4']),
('E60', 'Defensa India de Rey', ARRAY['d4','Nf6','c4','g6']),
('E70', 'India de Rey: Sistema Clásico', ARRAY['d4','Nf6','c4','g6','Nc3','Bg7','e4','d6']),
('E90', 'India de Rey: Sistema Ortodoxo', ARRAY['d4','Nf6','c4','g6','Nc3','Bg7','e4','d6','Nf3','O-O']);
